# Generated by Django 5.2.7 on 2025-11-29 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Especialidad', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='especialidad',
            options={'ordering': ['tipo'], 'permissions': [('puede_gestionar_especialidades', 'Puede gestionar especialidades')], 'verbose_name': 'Especialidad', 'verbose_name_plural': 'Especialidades'},
        ),
        migrations.AddField(
            model_name='especialidad',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='especialidad',
            name='doctor',
            field=models.CharField(max_length=150, verbose_name='Doctor'),
        ),
        migrations.AlterField(
            model_name='especialidad',
            name='tipo',
            field=models.CharField(max_length=100, verbose_name='Tipo de Especialidad'),
        ),
    ]
