# Generated by Django 5.2.7 on 2025-10-12 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Turnos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='fecha',
            field=models.DateField(),
        ),
    ]
