# Generated by Django 5.2.7 on 2025-11-17 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Turnos', '0002_alter_turno_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='pago_senia',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='turno',
            name='pago_total',
            field=models.BooleanField(default=False),
        ),
    ]
