# Generated by Django 5.2.7 on 2025-11-22 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Turnos', '0003_turno_pago_senia_turno_pago_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='obrasocial',
            field=models.CharField(blank=True, null=True),
        ),
    ]
