# Generated by Django 5.2.7 on 2025-11-22 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Turnos', '0005_turno_estado_pago_turno_monto_pagado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
