# Generated by Django 5.2.7 on 2025-11-29 19:05

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Especialidad', '0002_alter_especialidad_options_especialidad_activo_and_more'),
        ('Turnos', '0006_turno_email'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='turno',
            options={'ordering': ['-fecha', '-fecha_creacion'], 'permissions': [('puede_ver_todos_turnos', 'Puede ver todos los turnos'), ('puede_gestionar_turnos', 'Puede gestionar turnos')], 'verbose_name': 'Turno', 'verbose_name_plural': 'Turnos'},
        ),
        migrations.AddField(
            model_name='turno',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='turno',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='turno',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 11, 29, 19, 5, 37, 103639, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='turno',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turnos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='turno',
            name='dni',
            field=models.IntegerField(verbose_name='DNI'),
        ),
        migrations.AlterField(
            model_name='turno',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='turno',
            name='especialidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnos', to='Especialidad.especialidad'),
        ),
        migrations.AlterField(
            model_name='turno',
            name='estado_pago',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20, verbose_name='Estado del Pago'),
        ),
        migrations.AlterField(
            model_name='turno',
            name='fecha',
            field=models.DateField(verbose_name='Fecha del turno'),
        ),
        migrations.AlterField(
            model_name='turno',
            name='monto_pagado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Monto Pagado'),
        ),
        migrations.AlterField(
            model_name='turno',
            name='obrasocial',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Obra Social'),
        ),
        migrations.AlterField(
            model_name='turno',
            name='paciente',
            field=models.CharField(max_length=200, verbose_name='Paciente'),
        ),
        migrations.AlterField(
            model_name='turno',
            name='pago_senia',
            field=models.BooleanField(default=False, verbose_name='Pago Seña'),
        ),
        migrations.AlterField(
            model_name='turno',
            name='pago_total',
            field=models.BooleanField(default=False, verbose_name='Pago Total'),
        ),
    ]
