# Generated by Django 5.2.7 on 2025-12-03 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Turnos', '0007_alter_turno_options_turno_activo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='tipo_pago',
            field=models.CharField(blank=True, choices=[('completo', 'Pago Completo'), ('senia', 'Seña')], max_length=20, null=True, verbose_name='Tipo de Pago'),
        ),
    ]
